name: worldsmith
version: 0.17.0
description: A library for creating RPGs using [ziggurat](https://pub.dev/packages/ziggurat).
repository: https://github.com/chrisnorman7/worldsmith
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_sdl: ^0.8.6
  dart_synthizer: ^0.7.7
  encrypt: ^5.0.1
  json_annotation: ^4.4.0
  open_url: ^2.0.0
  path: ^1.8.0
  ziggurat: ^0.41.0
  ziggurat_sounds: ^0.21.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
executables:
  worldsmith: worldsmith
