name: worldsmith
version: 0.20.0
description: A library for creating RPGs using [ziggurat](https://pub.dev/packages/ziggurat).
repository: https://github.com/chrisnorman7/worldsmith
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_sdl: ^0.9.7
  dart_synthizer: ^0.9.0
  encrypt: ^5.0.1
  json_annotation: ^4.4.0
  open_url: ^2.0.0
  path: ^1.8.0
  ziggurat: ^0.43.1
  ziggurat_sounds: ^0.23.2

dev_dependencies:
  analyzer: ^4.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  lints: ^1.0.1
  test: ^1.16.0
executables:
  worldsmith: worldsmith
