name: worldsmith
version: 0.0.0
description: A library for creating RPGs using [ziggurat](https://pub.dev/packages/ziggurat).

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dart_sdl: ^0.8.6
  dart_synthizer: ^0.7.7
  json_annotation: ^4.4.0
  path: ^1.8.1
  ziggurat: ^0.32.0
  ziggurat_sounds: ^0.11.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
