name: worldsmith
version: 0.20.0
description: A library for creating RPGs using [ziggurat](https://pub.dev/packages/ziggurat).
repository: https://github.com/chrisnorman7/worldsmith

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  dart_sdl: ^0.10.0
  dart_synthizer: ^0.10.0
  encrypt: ^5.0.1
  json_annotation: ^4.5.0
  open_url: ^2.0.0
  path: ^1.8.1
  ziggurat: ^0.48.1
  ziggurat_sounds: ^0.28.1

dev_dependencies:
  analyzer: ^4.1.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.1

executables:
  worldsmith: worldsmith
